baseURL = "https://www.dantezulli.ar"
title = "dantezulli.ar 🇦🇷"
copyright = "Dante Zulli (CC BY 4.0)"
defaultContentLanguage = "es"
languageCode = "es-AR"
enableRobotsTXT = true

[[menu.main]]
  name = "now"
  url = "/now/"
  weight = 1
[[menu.main]]
  name = "blog"
  url = "/blog/"
  weight = 2
[[menu.main]]
  name = "proyectos"
  url = "/proyectos/"
  weight = 3
[[menu.main]]
  name = "rss"
  url = "/index.xml"
  weight = 4

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[params]
  title = "dantezulli.ar"
  description = "Blog personal de Dante Zulli"
  # favicon = "images/favicon.png"
  dateFormat = "2006-01-02"
  generateSocialCard = true
  madeWith = "Basado en [Bear Cub](https://github.com/clente/hugo-bearcub)"
  [params.social]
    linkedin = "dante-zulli"
  [params.author]
    name = "Dante Zulli"
    email = "dantezulli2004@gmail.com"
